In [5]:
import torch
import customconv2d

In [6]:
input_image = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]], dtype=torch.float32)
kernel = torch.tensor([[1.0, 0.0], [0.0, -1.0]], dtype=torch.float32)

input_image_pytorch = input_image.unsqueeze(0).unsqueeze(0)
kernel_pytorch = kernel.unsqueeze(0).unsqueeze(0)

In [10]:
output_custom = customconv2d.conv2d(input_image.numpy(), kernel.numpy(), stride=1, padding=1)
output_custom_torch = torch.tensor(output_custom, dtype=torch.float32)

In [13]:
print("Output from custom conv2d:\n", output_custom_torch.numpy())

Output from custom conv2d:
 [[-1. -2. -3.  0.]
 [-4. -4. -4.  3.]
 [-7. -4. -4.  6.]
 [ 0.  7.  8.  9.]]
